\
#include "models.h"

Database::Database() {
    PBoycottes.append({"Nestle","5901234123457","Entreprise boycottee pour sa politique en Palestine"});
    PBoycottes.append({"Coca-Cola","8456789012346","Entreprise boycottee pour son soutien indirect"});
    PBoycottes.append({"Pepsi","7612345678902","Entreprise boycottee pour ses filiales"});
    PBoycottes.append({"McDonald's","4215678932104","Soutien controverse a certaines operations"});
    PBoycottes.append({"Kellogg's","3309876543215","Partenariat conteste"});
    PBoycottes.append({"Mars","9781234567897","Soutien indirect"});
    PBoycottes.append({"Unilever","5012349987120","Entreprise impliquee"});
    PBoycottes.append({"Cadbury", "8801122334459", "Filiale controversee"});
    PBoycottes.append({"Mondelez", "6928374651208", "Soutien indirect"});
    PBoycottes.append({"Danone", "4009871236549", "Partenaire conteste"});
    PBoycottes.append({"Tyson Foods", "7356001234581", "Entreprise boycottee"});
    PBoycottes.append({"Perdue Farms", "5609988776654", "Soutien indirect"});
    PBoycottes.append({"Hormel Foods", "4823490012783", "Collaboration controversee"});
    PBoycottes.append({"Nestle KitKat", "8012345678125", "Filiale impliquee"});
    PBoycottes.append({"Starbucks", "5207765432108", "Soutien indirect"});
    PBoycottes.append({"Heinz", "6931200456783", "Entreprise boycottee"});
    PBoycottes.append({"Chiquita", "9123456009875", "Soutien conteste"});
    PBoycottes.append({"Dole", "3256007891236", "Entreprise impliquee"});
    PBoycottes.append({"General Mills", "0701234567894", "Soutien indirect"});
    PBoycottes.append({"Nestle Nesquik", "9501122334468", "Filiale contestee"});

    SBoycottes.append({"Facebook","www.facebook.com","Soutien indirect a certaines activites contestees"});
    SBoycottes.append({"Instagram","www.instagram.com","Entreprise impliquee dans des pratiques controversees"});
    SBoycottes.append({"YouTube","www.youtube.com","Partenariats contestes"});
    SBoycottes.append({"WhatsApp", "www.whatsapp.com", "Soutien indirect a certaines politiques"});
    SBoycottes.append({"Twitter ", "www.twitter.com", "Entreprise impliquee dans certaines controverses"});
    SBoycottes.append({"Netflix", "www.netflix.com", "Contenu ou partenariat discute"});
    SBoycottes.append({"Amazon", "www.amazon.com", "Pratiques commerciales contestees"});
    SBoycottes.append({"Google", "www.google.com", "Entreprise impliquee indirectement"});
    SBoycottes.append({"Microsoft", "www.microsoft.com", "Partenariats controverses"});
    SBoycottes.append({"Airbnb", "www.airbnb.com", "Presence dans des zones contestees"});
    SBoycottes.append({"Intel", "www.intel.com", "Soutien indirect"});
    SBoycottes.append({"HP", "www.hp.com", "Entreprise impliquee dans certaines filiales"});
    SBoycottes.append({"Coca-Cola", "www.coca-cola.com", "Soutien indirect ou filiales problematiques"});
    SBoycottes.append({"Nestle", "www.nestle.com", "Entreprise boycottee pour sa politique en Palestine"});
    SBoycottes.append({"Unilever", "www.unilever.com", "Filiales controversees"});
    SBoycottes.append({"Disney", "www.disney.com", "Soutien indirect a certaines pratiques"});
    SBoycottes.append({"McDonald's", "www.mcdonalds.com", "Presence contestee dans certaines zones"});
    SBoycottes.append({"Starbucks", "www.starbucks.com", "Soutien indirect a certaines activites"});
    SBoycottes.append({"Chiquita", "www.chiquita.com", "Entreprise impliquee"});
    SBoycottes.append({"Dole", "www.dole.com", "Soutien indirect a certaines filiales"});
    SBoycottes.append({"Adidas", "www.adidas.com", "Entreprise impliquee"});
    SBoycottes.append({"Nike", "www.nike.com", "Soutien indirect"});

    PAlternatifs.append({"Delice","6191234000015","Produit tunisien, marque locale"});
    PAlternatifs.append({"SICAM","6191234000022","Entreprise tunisienne independante"});
    PAlternatifs.append({"Nutrina","6191234000039","Produit naturel et local"});
    PAlternatifs.append({"Boga", "6191234000053", "Entreprise tunisienne, fabrication locale"});
    PAlternatifs.append({"Napolis", "6191234000046", "Marque tunisienne ethique"});
    PAlternatifs.append({"Saida", "6191234000060", "Produit tunisien responsable"});
    PAlternatifs.append({"Al Waha", "6191234000077", "Marque locale et independante"});
    PAlternatifs.append({"Carthage", "6191234000084", "Production locale et durable"});
    PAlternatifs.append({"Cristaline","6194001800814","Eau minirale 100% tunisienne"});
    PAlternatifs.append({"Zitouna", "6191234000091", "Produit tunisien artisanal"});
    PAlternatifs.append({"Maison du Miel", "6191234000107", "Apiculture locale et independante"});
    PAlternatifs.append({"Sanebil", "6191234000114", "Produit tunisien bio"});
    PAlternatifs.append({"Ben Yeder", "6191234000121", "Entreprise locale ethique"});
    PAlternatifs.append({"Nebli", "6191234000138", "Produit tunisien artisanal"});
    PAlternatifs.append({"Grain d'Or", "6191234000145", "Marque tunisienne independante"});
    PAlternatifs.append({"Viva", "6190345829173", "Boisson tunisienne"});
    PAlternatifs.append({"Choco Délice", "6198534217960", "Chocolats tunisiens"});
    PAlternatifs.append({"Fructis", "6199087345621", "Marque tunisienne"});
    PAlternatifs.append({"El Kef Conserves", "6193487201958", "Conserves tunisiennes"});
    PAlternatifs.append({"Caprera", "6199820154376", "Pâtes tunisiennes"});
    PAlternatifs.append({"Grano Vita", "6194529081374", "Pâtes locales"});

    SAlternatifs.append({"Mosaique FM","www.mosaiquefm.net","Alternative tunisienne aux reseaux internationaux"});
    SAlternatifs.append({"Nessma TV","www.nessma.tv","Plateforme media tunisienne"});
    SAlternatifs.append({"Kapitalis", "www.kapitalis.com", "Actualites tunisiennes"});
    SAlternatifs.append({"WePlay","www.weplayapp.com","application arabienne"});
    SAlternatifs.append({"Friv","www.friv.com","pas de soutien ni financièrement et ni politiquement "});
    SAlternatifs.append({"Business News", "www.businessnews.com.tn", "Portail d'information tunisien"});
    SAlternatifs.append({"Cityphone","www.cityphonetn.com","Boutiques tunisienne"});
    SAlternatifs.append({"El Hiwar Ettounsi", "www.elhiwarettounsi.com", "Chaine tunisienne en ligne"});
    SAlternatifs.append({"Mosaique TV", "www.mosaiquefm.net/tv", "Videos et streaming tunisien"});
    SAlternatifs.append({"Watania Replay", "www.watania1.tn", "Streaming tunisien officiel"});
    SAlternatifs.append({"Jumia Tunisie", "www.jumia.com.tn", "Alternative tunisienne a Amazon"});
    SAlternatifs.append({"MyTek", "www.mytek.tn", "E-commerce informatique tunisien"});
    SAlternatifs.append({"TunisieNet", "www.tunisianet.com.tn", "Boutique informatique tunisienne"});
    SAlternatifs.append({"Tdiscount", "www.tdiscount.tn", "Marketplace tunisienne"});
    SAlternatifs.append({"Founa", "www.founa.com", "E-commerce tunisien generaliste"});
    SAlternatifs.append({"Shoppex", "www.shoppex.tn", "Marketplace tunisienne variee"});
    SAlternatifs.append({"ClickToBuy", "www.clicktobuy.tn", "Boutique en ligne tunisienne"});
    SAlternatifs.append({"TechnoSoft", "www.technosoft.com.tn", "Boutique informatique locale"});
    SAlternatifs.append({"ZitounaPay", "www.zitounapay.com", "Service de paiement tunisien"});
    SAlternatifs.append({"TanitJobs", "www.tanitjobs.com", "Alternative tunisienne a LinkedIn"});

    Quotes.append("“Boycott is a nonviolent weapon against injustice.”");
    Quotes.append("“Oppression anywhere is a threat to freedom everywhere.”");
    Quotes.append("“Peace is impossible without justice; justice is impossible without freedom.”");
    Quotes.append("“Supporting Palestine is a moral responsibility, not a choice.”");
    Quotes.append("“When one voice is silenced, many must speak louder.”");
    Quotes.append("“Empathy knows no borders; human dignity knows no occupation.”");
    Quotes.append("“Freedom cannot exist where injustice thrives.”");
    Quotes.append("Your choices are your voice.");
    Quotes.append("“Noncooperation with evil is as much a duty as cooperation with good.” — Mahatma Gandhi");
    Quotes.append("Boycott is not hate; it is a demand for justice.");
    Quotes.append("We have the power to choose what we support and what we refuse.");
    Quotes.append("“To be silent in the face of injustice is to take the side of the oppressor.” — Desmond Tutu");
    Quotes.append("No one is more powerful than the people when they act together.");
    Quotes.append("Freedom and dignity are rights, not privileges.");
    Quotes.append("“Supporting Palestine is about standing for human dignity and rights.”");
    Quotes.append("Boycott is a peaceful form of resistance.");
    Quotes.append("To boycott is to refuse to profit from injustice.");
    Quotes.append("“The occupied deserve voices, not walls.”");
    Quotes.append("“We are stronger when we resist injustice together.”");
    Quotes.append("“Freedom is the birthright of every Palestinian child.”");
    Quotes.append("“Justice delayed is justice denied; Palestine deserves justice now.”");
    Quotes.append("“Silence in the face of oppression is complicity.”");

    Articles.append(Article{"BDS MOUVEMENT– Official Website", "https://bdsmovement.net"});
    Articles.append(Article{"“BDS Explained in 5 Minutes” – AJ+","https://www.youtube.com/watch?v=3h0eSyz_hdE"});
    Articles.append(Article{"Amnesty International – Reports on Israel/Palestine","https://www.amnesty.org/en/location/middle-east-and-north-africa/israel-and-occupied-palestinian-territories/"});
    Articles.append(Article{"Human Rights Watch (HRW) – Reports","https://www.hrw.org/middle-east/n-africa/israel/palestine"});
    Articles.append(Article{"Middle East Eye","https://www.middleeasteye.net/topics/palestine"});
    Articles.append(Article{"Electronic Intifada","https://electronicintifada.net"});
    Articles.append(Article{"UN OCHA – Occupied Palestinian Territory","https://www.ochaopt.org"});
    Articles.append(Article{"“Why People Boycott Israel” – Vice News","https://www.youtube.com/watch?v=J3xU6_lJx8g"});
    Articles.append(Article{"“Palestine: Stories of Resistance” – Middle East Eye","https://www.youtube.com/watch?v=F7pGxvR0V6k"});
    Articles.append(Article{"“The War on Gaza” – Al Jazeera Investigative Report","https://www.youtube.com/watch?v=XbKq6_Q7aB0"});

    BooksTitle.append("“The Question of Palestine” – Edward W. Said");
    BooksTitle.append("“Palestine: Peace Not Apartheid” – Jimmy Carter");
    BooksTitle.append("“Gaza: An Inquest into Its Martyrdom” – Norman Finkelstein");
    BooksTitle.append("“The Ethnic Cleansing of Palestine” – Ilan Pappé");
    BooksTitle.append("“BDS: Boycott, Divestment, Sanctions: The Global Struggle for Palestinian Rights” – Omar Barghouti");
    BooksTitle.append("“Palestinian Walks: Forays into a Vanishing Landscape” – Raja Shehadeh");
    BooksTitle.append("“Living Palestine: A Personal Account of Life Under Occupation” – Rashid Khalidi");
    BooksTitle.append("“Blaming the Victims: Spurious Scholarship and the Palestinian Question” – Edward W. Said & Christopher Hitchens");
    BooksTitle.append("“The BDS Movement: A Global Campaign for Palestinian Rights”");
    BooksTitle.append("“Footnotes in Gaza” – Joe Sacco");
    BooksTitle.append("'The Iron Cage: The Story of the Palestinian Struggle for Statehood' – Rashid Khalidi");
    BooksTitle.append("'Palestine: A Four Thousand Year History' – Nur Masalha");
    BooksTitle.append("'Gaza in Crisis: Reflections on Israel's War Against the Palestinians' – Noam Chomsky & Ilan Pappé");
    BooksTitle.append("'The Battle for Justice in Palestine' – Ali Abunimah");
    BooksTitle.append("'Under the Cover of War: The Zionist Expulsion of the Palestinians' – Ian Black");
    BooksTitle.append("'Palestine: A Social History' – Samih K. Farsoun");
    BooksTitle.append("'In Search of Fatima: A Palestinian Story' – Ghada Karmi");
    BooksTitle.append("'The Hundred Years’ War on Palestine' – Rashid Khalidi");
    BooksTitle.append("'Israel/Palestine: How to End the War of 1948' – Tanya Reinhart");

}
